// This file is part of a Rust reimplementation of the CDP System, a
// Composers Desktop Project (CDP) command-line sound-processing suite
// originally written by Trevor Wishart, Richard Dobson, Martin Atkins
// and others (see legacy/dev for the original C source and its
// per-file copyright notices).
//
// SPDX-License-Identifier: LGPL-2.1-or-later
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation, either version 2.1 of
// the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this program. If not, see
// <https://www.gnu.org/licenses/>.

//! Tests against real files, with expected values taken independently
//! (via `legacy` `sndinfo props`, and by hand-parsing the RIFF chunks
//! with a short Python script -- not derived from this crate's own
//! code, so a bug shared between the check and the implementation
//! cannot hide here).

use cdp_sf::{
    FileKind, PropertyBlock, SampleType, SoundFile, SoundFileWriter, SpectralInfo, WriteSpec,
};

/// `crates/cdp-sf/tests/fixtures/synth_stereo_16bit.wav`, generated by
/// the legacy `synth wave 1 sinef.wav 44100 2 1 440` and confirmed
/// against `legacy` `sndinfo props`:
///
/// ```text
/// A SOUND file.
/// samples: ............ 88200
/// file type: ........... SOUND
/// sample rate: ........ 44100
/// channels: ........... 2
/// sample type:  16bit
/// PEAK data at: ...
/// CH 1: amp = 1.0000 (-0.00 dB) Frame 877
/// CH 2: amp = 1.0000 (-0.00 dB) Frame 877
/// ```
///
/// The exact PEAK bytes were extracted independently with a small
/// Python script that parses the RIFF chunks by hand (not this
/// crate), giving `0.999991238117218` rather than the 4-decimal
/// `1.0000` sndinfo prints.
#[test]
fn synth_generated_stereo_16bit_matches_legacy_sndinfo() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/synth_stereo_16bit.wav"
    );
    let sf = SoundFile::open(path).expect("should open a file synth itself wrote");

    assert_eq!(sf.fmt.channels, 2);
    assert_eq!(sf.fmt.sample_rate, 44100);
    assert_eq!(sf.fmt.bits_per_sample, 16);
    assert_eq!(sf.fmt.sample_type, SampleType::Short16);
    assert_eq!(sf.frame_count(), 44100);
    assert_eq!(sf.sample_count(), 88200); // legacy: "samples: ... 88200"

    assert_eq!(sf.peaks.len(), 2);
    for ch in &sf.peaks {
        assert_eq!(ch.position, 877);
        assert!(
            (ch.value - 0.999_991_24).abs() < 1e-6,
            "peak value {} does not match the independently-verified 0.999991238117218",
            ch.value
        );
    }

    let samples = sf
        .samples_f32()
        .expect("16-bit PCM decoding is implemented");
    assert_eq!(samples.len(), 88200);
    // The decoded peak (== the loudest decoded sample) should match
    // the PEAK chunk's own value at the tolerance a 16-bit quantised
    // sample can represent (1 / 32767).
    let decoded_peak = samples.iter().fold(0.0f32, |m, &s| m.max(s.abs()));
    assert!((decoded_peak - sf.peaks[0].value).abs() < 1.0 / 32767.0);
}

/// `docs/manual/sounds/marimba.wav`, part of the Learning Manual
/// corpus this repository already ships (see docs/migration/PLAN.md
/// section 5's test corpus note). Confirmed against `legacy`
/// `sndinfo props`:
///
/// ```text
/// A SOUND file.
/// samples: ............ 44174
/// file type: ........... SOUND
/// sample rate: ........ 44100
/// channels: ........... 1
/// sample type:  16bit
/// No PEAK chunk in this fileDate: Wed Jul 19 08:50:04 2000
/// ```
///
/// This file predates the PEAK chunk convention (no `PEAK` chunk) but
/// does carry a `DATE` property, giving coverage for both of those
/// paths. The exact `DATE` value (963996604) was computed
/// independently with `calendar.timegm((2000,7,19,8,50,4,0,0,0))` and
/// cross-checked by hand-decoding the file's `sfif` property bytes
/// (`BC6B7539` little-endian) in Python.
#[test]
fn real_corpus_file_without_peak_chunk_but_with_date_property() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/manual/sounds/marimba.wav"
    );
    let sf = SoundFile::open(path).expect("marimba.wav ships in this repository");

    assert_eq!(sf.fmt.channels, 1);
    assert_eq!(sf.fmt.sample_rate, 44100);
    assert_eq!(sf.fmt.sample_type, SampleType::Short16);
    assert_eq!(sf.sample_count(), 44174);

    assert!(sf.peaks.is_empty(), "this file predates the PEAK chunk");
    assert_eq!(
        sf.properties.get_i32("DATE").unwrap(),
        963_996_604,
        "DATE property should decode to Wed Jul 19 08:50:04 2000 UTC"
    );
}

/// `docs/manual/sounds/ws2/tsw1-2nd.aiff`, confirmed against `legacy`
/// `sndinfo props`:
///
/// ```text
/// samples: ............ 241102
/// sample rate: ........ 44100
/// channels: ........... 1
/// sample type:  16bit
/// PEAK data at: Sun Jun 25 20:48:42 2006
/// CH 1: amp = 0.2997 (-10.47 dB) Frame 29914
/// ```
///
/// Every field here (including the exact `PEAK` value/position/
/// timestamp and the `DATE` property) was independently confirmed by
/// hand-decoding the file's raw big-endian `COMM`/`PEAK`/`APPL` chunk
/// bytes (`xxd`), not by running this crate's own parser: `COMM`'s
/// 80-bit extended-float sample rate is `40 0E AC 44 00 00 00 00 00
/// 00`; `PEAK`'s payload is version `1`, timestamp `0x449EF6AA`
/// (1151268522, matching `sndinfo`'s date), channel value `0x3E997533`
/// (a big-endian `f32`, 0.299722284) and position `0x000074DA`
/// (29914); and the `sfif` property text starts `DATE\nAAF69E44\n`,
/// which as little-endian bytes is the same `0x449EF6AA` timestamp.
#[test]
fn real_aiff_corpus_file_matches_legacy_sndinfo_and_hand_decoded_chunks() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/manual/sounds/ws2/tsw1-2nd.aiff"
    );
    let sf = SoundFile::open(path).expect("ships in this repository");

    assert_eq!(sf.fmt.channels, 1);
    assert_eq!(sf.fmt.sample_rate, 44100);
    assert_eq!(sf.fmt.bits_per_sample, 16);
    assert_eq!(sf.fmt.sample_type, SampleType::Short16);
    assert_eq!(sf.sample_count(), 241_102);

    assert_eq!(sf.peak_timestamp, Some(1_151_268_522));
    assert_eq!(sf.peaks.len(), 1);
    assert!((sf.peaks[0].value - 0.299_722_28).abs() < 1e-6);
    assert_eq!(sf.peaks[0].position, 29_914);

    assert_eq!(sf.properties.get_i32("DATE").unwrap(), 1_151_268_522);

    let samples = sf.samples_f32().unwrap();
    assert_eq!(samples.len(), 241_102);
    let decoded_peak = samples.iter().fold(0.0f32, |m, &s| m.max(s.abs()));
    assert!((decoded_peak - sf.peaks[0].value).abs() < 1.0 / 32767.0);
}

/// `docs/manual/data/capm.ana`, confirmed against `legacy` `sndinfo
/// props`:
///
/// ```text
/// An ANALYSIS file.
/// samples: ............ 2901528
/// file type: .......... ANALYSIS DATA
/// channels: ........... 1026
/// original sample rate: 44100
/// analysis rate: ...... 344.531250
/// analysis window len:  1024
/// decimation factor: .. 128
/// ```
///
/// `arate`'s raw bytes (`strings`: `0044AC43`, little-endian) decode
/// to `344.53125` with an independent Python `struct.unpack('<f',
/// ...)`, matching `sndinfo`'s rounded `344.531250`.
#[test]
fn real_analysis_file_matches_legacy_sndinfo() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/manual/data/capm.ana"
    );
    let sf = SoundFile::open(path).expect("ships in this repository");

    assert_eq!(sf.fmt.channels, 1026);
    assert_eq!(sf.fmt.sample_type, SampleType::Float32);
    assert_eq!(sf.sample_count(), 2_901_528);
    assert_eq!(
        sf.file_kind,
        FileKind::Analysis(SpectralInfo {
            original_sample_size: 0,
            original_sample_rate: 44100,
            analysis_rate: 344.53125,
            analysis_window_length: 1024,
            decimation_factor: 128,
        })
    );
}

/// `docs/manual/data/crklenv.evl`, confirmed against `legacy`
/// `sndinfo props`:
///
/// ```text
/// A binary ENVELOPE file.
/// samples: ............ 2845
/// channels: ........... 1
/// window size: ........ 2.902494 ms
/// ```
#[test]
fn real_envelope_file_matches_legacy_sndinfo() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../docs/manual/data/crklenv.evl"
    );
    let sf = SoundFile::open(path).expect("ships in this repository");

    assert_eq!(sf.fmt.channels, 1);
    assert_eq!(sf.sample_count(), 2845);
    match sf.file_kind {
        FileKind::Envelope { window_size } => {
            assert!((window_size - 2.902_494).abs() < 1e-5);
        }
        other => panic!("expected FileKind::Envelope, got {other:?}"),
    }
}

/// A file this crate's own writer produces, with a `DATE` property
/// and a `cue ` chunk, must be readable by `legacy` `sndinfo props`
/// itself -- not just by this crate's own reader, which could share a
/// bug with the writer. Requires the `cdp8-postmerge` Docker image;
/// skipped (not failed) when Docker is unavailable, the same way
/// `tests/aiff_corpus.rs`'s live cross-check is.
#[test]
fn a_file_this_crate_writes_with_properties_is_readable_by_legacy_sndinfo() {
    let mut properties = PropertyBlock::new();
    properties.set_i32("DATE", 963_996_604);
    let spec = WriteSpec {
        channels: 1,
        sample_rate: 44100,
        sample_type: SampleType::Short16,
        write_peaks: true,
        properties,
        write_cue_chunk: true,
    };
    let mut w = SoundFileWriter::new(spec);
    let sine: Vec<f32> = (0..4410)
        .map(|n| (2.0 * std::f32::consts::PI * 440.0 * n as f32 / 44100.0).sin())
        .collect();
    w.write_frames(&sine);

    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("written_with_properties.wav");
    w.finalize(&path).unwrap();

    let output = std::process::Command::new("docker")
        .args([
            "run",
            "--rm",
            "-v",
            &format!("{}:/m:ro", dir.path().display()),
            "cdp8-postmerge:latest",
            "sndinfo",
            "props",
            "/m/written_with_properties.wav",
        ])
        .output();
    let Ok(output) = output else {
        eprintln!("docker unavailable, skipping live cross-check");
        return;
    };
    if !output.status.success() {
        panic!(
            "legacy sndinfo props failed on a file this crate wrote:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("channels: ........... 1"),
        "unexpected sndinfo output:\n{stdout}"
    );
    assert!(
        stdout.contains("Date: Wed Jul 19 08:50:04 2000"),
        "sndinfo should decode our DATE property back to the same date marimba.wav's does:\n{stdout}"
    );
}
