description = "error case: the required shift argument is absent"
program = "housekeep"
subcommand = "extract"
argv = [
    "extract",
    "4",
    "in.wav",
    "out.wav",
]

[[inputs]]
name = "in.wav"
from = "docs/manual/sounds/marimba.wav"

[expected]
exit_code = 255
stdout = """
Insufficient parameters on command line.


"""
stderr = ""

[expected.outputs]
